dbt_meshify/dbt_meshify.py
dbt_meshify/dbt_projects.py
dbt_meshify/main.py

This updates the `split` command to take a prompt for a project name, a selector(s), and the resulting resources into a simple dictionary for later use. 
Not at all married to the design of any of it, mostly just wanted to prove out the use of the Python API to do a `dbt ls` to get the components of a subproject.

Generate subprojects

---

dbt_meshify/main.py
tests/integration/test_contract_command.py

Closes #30
This PR cleans up the click params for 
- select
- exclude
- project-dir
- selector 
which are common for most commands. 
this also adds stubbed functions for creating groups and versions, and an argument for the `connect` command
package help:
```zsh
dbt-meshify --help
Usage: dbt-meshify [OPTIONS] COMMAND [ARGS]...
Options:
--help  Show this message and exit.
Commands:
add-contract  Adds a contract to all selected models.
add-version   Increments a model version on all selected models.
connect       Connects multiple dbt projects together by adding all...
create-group  Add selected resources to a group
split         Splits dbt projects apart by adding all necessary dbt...
```
command help:
```
❯ dbt-meshify add-contract --help
Usage: dbt-meshify add-contract [OPTIONS]
Adds a …
```

simplify cli setup

---

.github/workflows/ci-tests-pytest.yml

Please merge this update today! [node 12 support dropping tomorrow](https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/) and these version updates to Github Actions get ahead of that. Resolves RELENG-144

update used gh actions ahead of node12 deprecation

---

dbt_meshify/storage/file_manager.py
dbt_meshify/storage/yaml_editors.py
tests/unit/test_add_contract_to_yml.py
tests/unit/test_add_group_and_access_to_model_yml.py
tests/unit/test_add_group_to_yml.py
tests/unit/test_add_version_to_yml.py

This PR is an attempt to simplify some existing code
1. Rework the `file_manager.py` -- these classes may still be a little heavier than we need -- effectively, I have reduced this down to a small wrapper around the `pathlib` read and write operations to handle yml in one go, rather than having two additional classes just to handle this usecase. In reality, these could just be functions, but opted to keep it within a class so we have read from and write to paths for use in the future where we're moving files between projects. 
2. Attempt to simplify the methods in our `dbt_meshify.py` file:
- pull out common operations into helper functions outside the classes
- rename some variables for clarity (full_yml_dict --> models_dict or groups_dict most notably) 
- pull out a couple common …

Code cleanup

---

dbt_meshify/storage/file_manager.py
poetry.lock
pyproject.toml

closes #49 
This PR adds the `ruamel.yaml` package for file management to properly indent dbt yaml files according to our preferred format. This is particularly relevant for indents from array objects. 
The override logic for the `YAML` class was [taken from their documentation site](https://yaml.readthedocs.io/en/latest/example.html#output-of-dump-as-a-string) as the recommended way to dump to a string object. 
before:
```yml
models:
- name: shared_model
config:
contract:
enforced: true
columns:
- name: id
data_type: integer
- name: colleague
data_type: varchar
```
after:
```yml
models:
- name: shared_model
config:
contract:
enforced: true
columns:
- name: id
data_type: integer
- name: colleague
data_type: varchar
```

use ruamel with proper indents

---

dbt_meshify/storage/file_manager.py

The demo showed long YAML lines being wrapped, generating a bigger diff than needed.
This should fix it

Add larger length size to prevent wrapping lines

---

.github/workflows/publish.yml

Created a github workflow to publish release of package to pypi
- created a new github environment "PypiProd" (to restrict the reviewers) 
- created a new tag protection rule (to restrict who can create new tags)
- added publish.yml to the repo following [this](https://pgjones.dev/blog/trusted-plublishing-2023/) article

add pypi publish workflow

---

README.md
dbt_meshify/cli.py
dbt_meshify/main.py
docs/index.md
tests/integration/test_create_group_command.py
tests/integration/test_group_command.py

This PR updates the CLI options for group owner creation. Whereas before we required the user to provide the name of the field being updated and the value, now we have explicit properties for `--owner-name` and `--owner-email`. Additional properties are also still accepted via the `--owner-properties` option, which parses a YAML string.
Old syntax:
```console
dbt-meshify group \
--owner name dave \
--owner email dave@example.org \
--owner foo bar \
test_group_2 
```
New syntax:
```console
dbt-meshify group \
--owner-name dave \
--owner-email dave@example.org \
--owner-properties '{foo: bar}' \
test_group_2 
```
Along the way, I also added an `owner` decorator that performs validation of `--owner-*` arguments to ensure that either a name or email is always provided (as per spec), and moved …

Feature: Update CLI for group creation to use explicit option names for group owner properties

---

dbt_meshify/cli.py
tests/integration/test_create_group_command.py
tests/unit/test_add_group_and_access_to_model_yml.py

Closes #76 
This PR uses a class from dbt to allow for `MultiOption` types for `--select`, `--exclude` and `--selector`
```
dbt-meshify group us -s my_model your_model
```
now it works!
This code was lifted from Core directly, so I feel pretty confident that it should work!

Multi option support for select

---

dbt_meshify/storage/file_manager.py
dbt_meshify/storage/yaml_editors.py

Update `DbtYAML` class to have quote preservation on by default. This is accomplished by setting `preserve_quotes = True` during initialization of the class.
Resolves: #66 
**Example Output**
```
- name: customer_type
description: Options are 'new' or 'returning', indicating if a customer has ordered more than once or has only placed their first order to date.
tests:
- accepted_values:
values: ["new", "returning"]
```

Feature: Enable quote preservation to DbtYAML class by default

---

dbt_meshify/storage/yaml_editors.py
dbt_meshify/utilities/grouper.py
tests/unit/test_resource_grouper_classification.py

Resolves: #86 
I've created a new class method called `clean_subgraph`, which creates a new subgraph that has all `test` nodes removed. This allows the `_generate_resource_group` to only consider access levels for non-test node connections. This will prevent nodes with only test child nodes from being marked as `private`.
A new unit test has been added to confirm functionality.

Fix: `ResourceGrouper` no longer considers `test` resources during access control inference step 

---

dbt_meshify/dbt.py
dbt_meshify/main.py
dbt_meshify/storage/yaml_editors.py
dbt_meshify/utilities/grouper.py
poetry.lock
pyproject.toml
test-projects/split/split_proj/models/_groups.yml
test-projects/split/split_proj/models/staging/__models.yml

resolves #68 
@nicholasyager tried my hand at using `loguru` for some basic logging messages here. very open to changing how we structure this and whether we use this package at all -- it's pretty straightforward to use, but I have never added logs to a cli app before, so I don't know what best practices to consider.

add logging info

---

dbt_meshify/cli.py
dbt_meshify/main.py

Resolves: #93
This PR implements a custom Click Command type called `TupleCompatibleCommand`, which has a custom usage string implementation which places the `[OPTION]` metavar at the end of the usage string. 
**Original**
```console
dbt-meshify split [OPTIONS] PROJECT_NAME
```
**Updated**
```console
dbt-meshify split PROJECT_NAME [OPTIONS]
```
This is important from a UX perspective, since `--select` and other type-typed options will eat all subsequent strings that are not themselves options. For example, 
```console
dbt-meshify split --select foo bar
```
will yield an error, since `bar` will be interpreted as part of the selector instead of as the project name.
Now, if users follow the example, we will have the following correct usage:
```console
dbt-meshify split bar --select foo
```

fix(cli): Create custom Command type to support custom Usage docs

---

dbt_meshify/cli.py
dbt_meshify/main.py
tests/integration/test_split_command.py

Closes #101 
This PR makes the `create-path` CLI arg supplied to the `split` command, well, work! It now accepts any direct or relative path, allowing end users to split their projects into any directory they'd like!

Fix create path

---

dbt_meshify/dbt_projects.py
dbt_meshify/linker.py
dbt_meshify/main.py
dbt_meshify/storage/dbt_project_editors.py
tests/integration/test_split_command.py

This turned into a bigger one than anticipated!
The current `split` command checks for children of the selected resources, and updates those refs to select from the newly generated project. What it does _not_ do is update the _parents_ of the selected nodes, and apply the same checks (contract, make public those models, and update the refs within the selected models to refer to the "parent" project)
When a subproject is created, list out the nodes that are cross project parents and children of the selected resources:
1. If there are both cross project parents and children of the selected nodes **_stop execution_** -- per our best practices, we should not allow for project cycles like this:
`a --> b --> a` is no good!
2. proceed as normal for boundary nodes - cross project children of …

update logic to accomodate child-only subprojects

---

dbt_meshify/dbt_projects.py
dbt_meshify/storage/dbt_project_editors.py
dbt_meshify/utilities/linker.py
test-projects/source-hack/src_proj_b/models/_sources.yml

Closes #126 
Pretty straighforward if you ask me!

cast all relation names to lowercase while evaluating dependencies

---

dbt_meshify/storage/dbt_project_editors.py
dbt_meshify/utilities/dependencies.py
tests/integration/test_connect_command.py

In issue #127, @graciegoheen found that a `dependencies.yml` file could be created during connection operations with duplicate projects listed. I was able to determine that this was happening due to the `update_dependencies_yml` file performing a bunch of file-level operations and thereby bypassing all of our handy serialization code. Instead, we can avoid this by using the `Project` `EntityType`, which allows us to instead return a `ResourceChange` with just the new project listing. No more will this method need to read the file's current state and attempt to update it manually. A _much_ better approach IMHO. Along the way, I added an integration test to keep an eye on this in the future.

Fix: Update `update_dependencies_yml` to return a `ResourceChange` and not a `FileChange`

---

dbt_meshify/dbt_projects.py
dbt_meshify/storage/dbt_project_editors.py
test-projects/split/split_proj/macros/_macros.yml

Closes #134 
This should properly resolve the patch path for documented macros! Otherwise, the `split.initialize()` function will fail when trying to `copy_resource_yml`

fix patch paths for macros

---

dbt_meshify/dbt_projects.py
test-projects/split/split_proj/macros/cents_to_dollars.sql
test-projects/split/split_proj/macros/type_numeric.sql
tests/integration/test_split_command.py

Merge #135 first! this has some extra commits
Closes #139 
This recursively checks any custom macros for their custom macro dependencies as well!

Fix macro parents

---

dbt_meshify/main.py

There was a typing issue in the `connect` cli command, where returning early would return None, which would trip up the change_set_procesor. I've added type hints to the connect function to prevent this error in the future, and set the early return to return an empty list.
Along the way, I updated the log record created when there are no project dependencies to be a warning instead of info. Ideally, this will make it more clear when there's nothing to be done.
Resolves #141

fix: Connecting disjoint projects does not raise NoneType error

---

README.md
dbt_meshify/main.py
dbt_meshify/utilities/grouper.py
tests/integration/test_group_command.py
tests/unit/test_add_group_and_access_to_model_yml.py
tests/unit/test_resource_grouper_classification.py

In issue #119, we discussed that it doesn't make sense for the default access level granted during grouping to be `public`, since that would provide unexpected cross-project access. This PR updates the default access level granted to instead be `protected`. This will ensure that all models in the project can access the model, without granting cross-project access.
Resolves: #119

Fix: Update default access used in group creation to `protected`

---

dbt_meshify/dbt_projects.py
dbt_meshify/utilities/references.py

resolves #143 
I will also split an additional issue out to track the question of "what happens if a downstream node has two cross-project parents?
this PR adds:
- logic to build the `child_map` and `parent_map` objects into dbt projects
- uses those maps to simplify and clarify the logic that detects cross project parents and children
- updates the logic in `update_child_refs` to _only evaluate children of the model called in the split operation_ (the original motivation of this PR!)

build and leverage child and parent maps to properly evaluate cross project dependencies

---

dbt_meshify/main.py
dbt_meshify/storage/dbt_project_editors.py
dbt_meshify/utilities/linker.py
dbt_meshify/utilities/references.py
test-projects/source-hack/dest_proj_a/models/downstream_model_2.sql
tests/integration/test_connect_command.py
tests/integration/test_dependency_detection.py
tests/integration/test_split_command.py

Resolves #147 
This PR adds some state awareness to the split and connect commands so that updates to ref functions are additive and not destructive!
When splitting:
1. if updating child refs, check the current list of changes for any already existing code changes to the target resource at the sql path. Use the data from that change instead of the raw code if there's a previous one
2. if updating the parent refs, use the code from the last update to the current resource. This iteration is happening on a per-child basis, so this function does not need the full list of current children 
When connecting
1. if updating child refs for package dependencies, check the current list of changes for any already existing code changes to the target resource at the sql path. Use the data from that …

Children of multiple boundary nodes

---

dbt_meshify/storage/dbt_project_editors.py
test-projects/split/split_proj/dbt_project.yml

The internal `Project` representation of the `require-dbt-versions` field within `dbt-core` is a list of strings, where each part of the version is an element in the list. When serialized in `write_project_file`, the resulting YAML is _also_ a list of strings. This PR adds some formatting to the `write_project_file` function to join the elements of the list into one complete string.
Resolves: #138 
```yml
name: "split_proj"
version: "1.0.0"
config-version: 2
profile: "split_proj"
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds", "jaffle_data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
require-dbt-version: ">=1.6.0"
clean-targets: # directories to be removed by `dbt clean`
- "target"
- "dbt_packages"
vars:
truncate_timespan_to: "{{ …
```

Fix: `require-dbt-versions` no longer serialized as a list of characters

---

dbt_meshify/main.py
test-projects/source-hack/src_proj_a/packages.yml
tests/integration/test_dependency_detection.py

If you are using the `--projects-dir` arg, and your projects have packages installed, the `glob` method we use will pick up those project_paths as well. SImilarly, global packages in your virtual environment, if your venv is in the `--projects-dir` will get picked up here too. 
This filters out projects that are in a directory containing `dbt_packages`  or `site-packages`

filter out package paths, local and global

---

dbt_meshify/main.py
test-projects/source-hack/src_proj_a/dbt_project.yml

closes #161 
When a project has hooks defined in `dbt_project.yml`, the target directory contains a subdirectory called `dbt_project.yml` that contains the compiled sql. Our current logic for the `connect` command will attempt to compile a project at that directory instead of ignoring it. 
This PR adds a check to ensure we only look at files, not directories.

ensure path is a file not a directory

---

dbt_meshify/dbt_projects.py
tests/integration/test_connect_command.py
tests/integration/test_contract_command.py
tests/integration/test_create_group_command.py
tests/integration/test_group_command.py
tests/integration/test_split_command.py
tests/integration/test_version_command.py

Previously, it was possible for a user to provide a project path that is not real. For instance, running the command in the wrong directory! In this PR, I've added a check to include that a `dbt_project.yml` file is present in the project path, and if not, a `DbtMeshifyException` is raised with a corresponding error message. Along the way, I added tests for each command to confirm that the correct error message is returned if an invalid project path is provided.
Resolves: #87 
```console
(dbt-meshify-py3.11) > $ dbt-meshify connect --project-paths test-projects/temp_proj/src_proj_a  test-projects/temp_proj/src_proj_b
19:50:17 | ERROR | The provided directory (/Users/nicholas/projects/nicholasyager/dbt-meshify/test-projects/temp_proj/src_proj_a) does not contain a dbt project.
```

Fix: Raise a DbtMeshifyError if a project path is provided that does not contain a `dbt_project.yml` file

---

dbt_meshify/change.py
dbt_meshify/main.py
dbt_meshify/utilities/linker.py
dbt_meshify/utilities/versioner.py
docs/examples.md
docs/index.md
tests/integration/test_version_command.py
tests/unit/test_add_version_to_yml.py

This PR makes some lofty changes to how versions are handled in dbt-meshify.
1. The `operation add-version` command ONLY adds version boilerplate for models that are currently unversioned.
2. A new `operation bump-version` command handles bumping versions for models, including prereleases and file operations.
3. A new `version` command, which does both! In this case, previously unversioned models will have version boilerplate added, and then the version will be incremented on top.
Resolves: #168

Feature: Separate the `add-version` command into `add-version` and `bump-version`. Create new `version` command.

---

dbt_meshify/dbt.py
tests/unit/test_dbt_projects.py

Closes #156 
This catches a `UninstalledPackagesFoundError` when parsing a dbt project, and runs deps automatically before parsing!
yabba dabba doo!

handle missing packages exception

---

dbt_meshify/utilities/references.py
tests/unit/test_update_ref_functions.py

This PR properly handles versioned refs when performing the regex replace to add the project argument during splitting. 
Closes #172

handle version args for ref updates in sql and python

---

dbt_meshify/utilities/versioner.py
tests/integration/test_version_command.py

In issue #177, it's observed that a `version` run failed due to an attempt to Copy a file to the same location as the source. This is a result of two bits of code interacting in unexpected ways:
1. The `load_model_yaml` file was failing due to the model being versioned not having YAML.
2. The `model_override` not being applied to the loaded model yaml, due to this logic being placed within the `try/except` block.
As a result, if a model missing YAML properties was being versioned, the output from `add_version` would not be added to `bump_version`, and it would fail.
Outside remedying this issue, there are two other systematic failures in place, too:
1. `bump_version` should not support un-versioned models. A new exception has been added to handle this, and tests have been updated …

Fix: Correct behavior of `version` for models missing YAML properties

---

.gitignore
dbt_meshify/dbt.py

Fixes #176 
Runs `dbt clean` before `dbt deps` when the packages installed don't match the packages in `packages.yml`
One of the use cases where clean is required for example is when people used to use `dbt_metrics` and then move to 1.6. Removing the package from `packages.yml` doesn't remove it from `dbt_packages` and still raise compilation errors.

176 clean before deps

---

dbt_meshify/main.py
tests/integration/test_group_command.py

closes #181
Makes sure we properly pass the read catalog flag to the second invocation nested in `dbt-meshify group` !

pass `--read-catalog` to both `group` subcommands

---

dbt_meshify/dbt_projects.py

This PR makes dbt-meshify compatible with the latest dbt core release by passing any multiselect args to `dbt ls` as a single string separated by spaces, which is accepted by the parser in dbt core. 
My initial implementation was to convert the tuple that is returned from our meshify command to a list, but that raised the same error as before -- if appears the type check we were discussing in our sync is not relevant for the `--select` flag, and is used for other flags. 
I tested on 1.6.3+, and these changes appear to work across versions

pass args as string

---

dbt_meshify/change.py
dbt_meshify/dbt_projects.py
dbt_meshify/main.py
dbt_meshify/storage/dbt_project_editors.py
dbt_meshify/storage/file_content_editors.py
dbt_meshify/storage/file_manager.py
dbt_meshify/storage/jinja_blocks.py
test-projects/split/split_proj/macros/_macros.yml
test-projects/split/split_proj/macros/cents_to_dollars.sql
test-projects/split/split_proj/models/docs.md
test-projects/split/split_proj/models/marts/__models.yml
test-projects/split/split_proj/models/staging/__models.yml
tests/integration/test_split_command.py
tests/unit/test_jinja_blocks.py

There are two PRs related to copying Jinja blocks to split dbt projects. One has to do with block-level copying of macros, to prevent multiple macros in the same file being copyied to a split project, and the other has to do with doc blocks not being copied over due to an absence of references. This PR resolves both issues.
1. This PR creates a new data structure for keeping track of `JinjaBlocks` at a character position level. This is accomplished by using `docs` and `macros` properties of a `Manifest`, coupled with some clever RegEx, to find where things start and end. Note that the RegEx may be brittle, so 👀 
2. Adds an `append` Operation to our file editors, allowing us to append-only edit files (like if we're moving a Jinja block from one place to another!).
3. Adds reference …

Feature: Block-level copying of Jinja content between split projects

---

dbt_meshify/utilities/contractor.py
tests/sql_and_yml_fixtures.py
tests/unit/test_add_contract_to_yml.py

closes #190 
As reported, when creating a contract, all column names are currently standardized to lowercase, even if the column was in uppercase in the original yml, leading to unintended duplications/overwriting. This PR adds a step to the Contractor class to maintain the original casing of each of the columns from the yml entry. Anything not defined in yml, but present in the catalog will continue to be lowercased. 
I could not figure out a clean way to pass dynamic column content to our pytest fixture in the unit tests, so i created a new model fixture that included the column specifications. I think that's a big code smelly, so open to suggestions.

Case sensitivity

---

dbt_meshify/dbt_projects.py
dbt_meshify/main.py
tests/integration/test_group_command.py

There was a small defect in `dbt-meshify`, in which the tool would ignore existing files that define groups, instead always defaulting to `_group.yml`. The desired behavior would be to default to a single file that already contains groups if one exists. To that end, I've implemented a check that finds all files that define groups, and if there is one and only one, it will default to that file. If there are none, it will use `_groups.yml`. If there are multiple, it will raise a fatal error and prompt the user to provide a `--group-file-yaml` path.
Along the way, I also added tests to confirm that the functionality works as expected.
Resolves: #188

Fix: The `group` command will check for existing group file paths.

---

dbt_meshify/storage/dbt_project_editors.py
dbt_meshify/utilities/references.py
test-projects/split/split_proj/macros/redirect.sql
test-projects/split/split_proj/models/marts/customers.sql
tests/integration/test_split_command.py

Currently, if a macro has an explicit `ref` to a model, and the macro is split into a new project, that ref will break. This PR implements `ref` rewrites so that the reference will become a two-argument `ref`.
Resolves: #189 
```console
(dbt-meshify-7d0CGWIh-py3.11) > $ dbt-meshify --debug split customers --project-path ./temp_proj --select customers                                          [±feature/macro_ref_rewrite ●(✹)]
11:36:08 | INFO | Executing dbt parse...
11:36:09 | INFO | Generating catalog with dbt docs generate...
11:36:09 | DEBUG | Registering the relationship between customers and its resources
11:36:09 | INFO | Selected 4 resources: {'model.split_proj.customers', 'test.split_proj.not_null_customers_customer_id.5c9bf9911d', …
```

Feature: Macros can re-write refs when split into new projects.

---

dbt_meshify/cli.py
dbt_meshify/main.py
tests/integration/test_cli_group.py

As mentioned in #198, there is a distinct need to have a `--version` flag added to `dbt-meshify` to make it easier for users to identify which version of `dbt-meshify` they have installed. This PR adds this functionality, such that running `dbt-meshify --version` will print the current version number from the package information (as stored w/in the internals of python), and exit.
To accomplish this, I added the new option, and then added the `invoke_without_command=True` argument to `click.group()` to allow us to run code in the `cli` group when a command has not been provided. I then manually implemented a default check to print help text if a subcommand has not been provided.
Resolves: #200 
```console
$ dbt-meshify --version
0.5.2                 
```
```console
$ dbt-meshify
Usage: …
```

Feature: Add  a `--version` flag to aid in debugging

---

dbt_meshify/change.py
dbt_meshify/change_set_processor.py
dbt_meshify/storage/dbt_project_editors.py
dbt_meshify/storage/file_content_editors.py
dbt_meshify/storage/file_manager.py
tests/integration/test_split_command.py

A common question for users of dbt-meshify is "why does the split project look ... odd?" In most cases, this is a byproduct of the existing `split` command creating only necessary directories and files in the split project. While functional, this is not the ideal experience for users.
This PR updates our method for creating projects, to instead start by creating a new starter project in the target directory, add all directories and files of interest, and then update the starter `dbt_project.yml` file using the sub-project's configuration information. The benefits to this approach are:
1. Sub-projects have all the standard files and directories for a dbt project.
2. The sub-project have a familiar `dbt_project.yml` file experience.
Along the way, I also implemented the following:
1. Tests …

Feature: Use dbt-core starter project as baseline for split projects

---

dbt_meshify/dbt_projects.py
test-projects/split/split_proj/models/marts/__models.yml
test-projects/split/split_proj/tests/generic/custom_generic_test.sql
tests/unit/test_jinja_blocks.py

When someone creates a custom generic test, it gets rendered as a macro in the manifest. this means that when we compile all the macros in the project during startup of the group and split commands, we fail to find the correct test block. 
this PR
- updates the args to the `JinjaBlock.from_file` call to be `test` and trims `test_` (which dbt adds) to find the name of the custom generic test block when the macro path is under `tests/generic/`
- adds a custom generic test to the split project to ensure this logic works!
submitted in partial fulfillment of #210

Fix for custom generic tests

---

dbt_meshify/storage/jinja_blocks.py
tests/unit/test_jinja_blocks.py

This PR solves the other half of beniots #210 !
This allows for list, dict, and newline characters in our jinja block search regex
I am sorry in advance, I branched from the other branch instead of main which i thought would be better but I see now is far worse. We should merge #211 first!

More jinja block escapes
